// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:spin_wheel_picker/app/data/models/spin_wheel.dart';
import 'package:spin_wheel_picker/app/data/models/wheel_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SpinWheelAdapter());
    registerAdapter(WheelItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SpinWheelAdapter());
    registerAdapter(WheelItemAdapter());
  }
}
