import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      // Common
      'settings': 'Settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'share': 'Share',
      'reset': 'Reset',
      'done': 'Done',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'no_data': 'No data',
      'add': 'Add',
      'create': 'Create',

      // Settings
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'about': 'About',
      'version': 'Version',
      'rate_app': 'Rate App',
      'privacy_policy': 'Privacy Policy',
      'remove_ads': 'Remove Ads',
      'premium_title': 'Premium',
      'premium_subtitle': 'Remove ads, unlock all features, and stay focused.',
      'premium_benefits': 'Premium Benefits',
      'premium_benefit_remove_ads': 'Remove ads',
      'premium_benefit_unlimited': 'Use all features without limits',
      'premium_benefit_statistics': 'View additional statistics',
      'premium_plan_title': 'Choose a plan',
      'premium_plan_weekly': 'Weekly',
      'premium_plan_weekly_desc': '1 week premium access',
      'premium_plan_monthly': 'Monthly',
      'premium_plan_monthly_desc': '30 days premium access',
      'premium_plan_yearly': 'Yearly',
      'premium_plan_yearly_desc': '365 days premium access',
      'premium_purchase': 'Start Premium',
      'premium_restore': 'Restore Purchase',
      'premium_owned': 'Premium is active',
      'premium_purchase_note': 'If your payment is completed, purchase will be restored automatically after app restart.',
      'purchase_error': 'Purchase Error',
      'purchase_unavailable': 'In-app purchase is not available now.',
      'purchase_failed': 'Purchase failed. Please try again.',
      'restore_error': 'Restore failed. Please try again.',
      'purchase_success': 'Purchase Completed',
      'premium_ready': 'Premium is now active.',
      'send_feedback': 'Send Feedback',
      'more_apps': 'More Apps',

      // App-specific
      'app_name': 'Spin Wheel',
      'spin': 'SPIN',
      'spinning': 'Spinning',
      'result': 'Result',
      'tap_to_close': 'Tap to dismiss',
      'history': 'RECENT',
      'no_history': 'Spin the wheel to get started!',
      'history_subtitle': 'Screen: @screen / Route: @route',
      'unknown_event': 'Unknown Event',
      'clear_all': 'Clear all',
      'items': 'items',
      'last_result': 'Last',
      'new_wheel': 'New Wheel',
      'wheel_name_hint': 'Wheel name...',
      'rename_wheel': 'Rename Wheel',
      'delete_wheel_confirm': 'Delete this wheel?',
      'no_wheels': 'No wheels yet',
      'no_wheels_desc': 'Create your first spin wheel\nto get started!',
      'edit_items': 'Edit Items',
      'add_item': 'Add Item',
      'edit_item': 'Edit Item',
      'item_hint': 'Item label...',
      'open_history': 'History',
      'open_stats': 'Stats',
    },
    'ko': {
      // 공통
      'settings': '설정',
      'save': '저장',
      'cancel': '취소',
      'delete': '삭제',
      'edit': '편집',
      'share': '공유',
      'reset': '초기화',
      'done': '완료',
      'ok': '확인',
      'yes': '예',
      'no': '아니요',
      'error': '오류',
      'success': '성공',
      'loading': '불러오는 중...',
      'no_data': '데이터 없음',
      'add': '추가',
      'create': '만들기',
      // 설정
      'dark_mode': '다크 모드',
      'language': '언어',
      'about': '앱 정보',
      'version': '버전',
      'rate_app': '앱 평가',
      'privacy_policy': '개인정보처리방침',
      'remove_ads': '광고 제거',
      'premium_title': '프리미엄',
      'premium_subtitle': '광고 제거, 추가 기능 잠금 해제, 끊김 없는 이용을 제공합니다.',
      'premium_benefits': '프리미엄 혜택',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_unlimited': '모든 기능 잠금 해제',
      'premium_benefit_statistics': '추가 통계 보기',
      'premium_plan_title': '요금제 선택',
      'premium_plan_weekly': '주간',
      'premium_plan_weekly_desc': '7일 프리미엄',
      'premium_plan_monthly': '월간',
      'premium_plan_monthly_desc': '30일 프리미엄',
      'premium_plan_yearly': '연간',
      'premium_plan_yearly_desc': '365일 프리미엄',
      'premium_purchase': '구매하기',
      'premium_restore': '구매 복원',
      'premium_owned': '프리미엄이 활성화됐어요',
      'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
      'purchase_error': '구매 오류',
      'purchase_unavailable': '인앱 결제를 사용할 수 없어요.',
      'purchase_failed': '결제에 실패했어요. 다시 시도해요.',
      'restore_error': '구매 복원에 실패했어요.',
      'purchase_success': '결제 완료',
      'premium_ready': '프리미엄이 활성화됐어요.',
      'send_feedback': '피드백 보내기',
      'more_apps': '더 많은 앱',
      // 앱 전용
      'app_name': '스핀 휠',
      'spin': '돌리기',
      'spinning': '돌아가는 중',
      'result': '결과',
      'tap_to_close': '탭하여 닫기',
      'history': '기록',
      'no_history': '기록이 없습니다',
      'history_subtitle': '화면: @screen / 경로: @route',
      'unknown_event': '알 수 없는 이벤트',
      'clear_all': '전체 삭제',
      'items': '항목',
      'last_result': '최근',
      'new_wheel': '새 휠',
      'wheel_name_hint': '휠 이름...',
      'rename_wheel': '휠 이름 변경',
      'delete_wheel_confirm': '이 휠을 삭제할까요?',
      'no_wheels': '휠이 없습니다',
      'no_wheels_desc': '첫 번째 스핀 휠을 만들어 시작하세요!',
      'edit_items': '항목 편집',
      'add_item': '항목 추가',
      'edit_item': '항목 편집',
      'item_hint': '항목 이름...',
      'open_history': '히스토리',
      'open_stats': '통계',
    },
  };
}



